### ISSUE TITLE
Issue with ConfigParser and checkout date when running pricing

### ISSUE THREAD

**Issue by realkibou** [JoeBashe/stl-scraper#2]
TypeError: Object of type ConfigParser is not JSON serializable
related to the checkout date: <configparser.ConfigParser object at 0x00000227C71784C0>

**Comment by realkibou** [comment]
There is a typo in .\command\stl_command.py

line 78 total = pricing.get_pricing(checkin, **checkout**, listing_id)

**Comment by JoeBashe** [comment]
Hi there, just saw this issue and have also pushed a fix for that. Thank you for catching that! :pray:
