### ISSUE TITLE
Run the scraper with anaconda

### ISSUE THREAD

**Issue by BoccheseGiacomo** [JoeBashe/stl-scraper#3]
I tried installing the scraper and running the commands for installation but using anaconda, because that's the only python i'm used to. i'm using a windows 11 os.

I created a new environment and ran the installation procedure inside it. 

All ok for installation, the trouble comes when running.

if i run ' ./stl.py search "Madrid, Spain" ' , i get: '.' is not recognized as an internal or external command
if i run ' stl.py search "Madrid, Spain" ' ,   i get opening the stl.py in visual studio code.

is this trouble due to the use of anaconda? or just my strange os settings?

**Comment by JoeBashe** [comment]
Hello @BoccheseGiacomo, thanks for your interest. 

I haven't tried running the project under anaconda, but theoretically I think it should be possible. That said, I think using `pip` would probably be easier.

`./stl.py` doesn't work in Windows. I think you may just need to reverse the backslash: `.\stl.py`. However you might need to explicitly call python: `python3 stl.py`. Hope that helps!

**Comment by JoeBashe** [comment]
@BoccheseGiacomo FYI I've added an option to run the project using the jupyter/scipy-notebook docker container, which contains conda. Closing this issue now, feel free to reopen if there are any additional questions. Thank you!
