### ISSUE TITLE
Reproducible docker environment with stl-scraper on Jupyter Notebook + Elasticsearch

### ISSUE THREAD

**Issue by aTnT** [JoeBashe/stl-scraper#9]
Hello,

Thanks you for creating and sharing this repo. I am trying to access the Calendar and Pricing functionality, which seems to require an elasticsearch database. I have written the below `docker-compose.yml` file:

```
version: "2.2"

services:
  jupyter-scipy-notebook:
    image: jupyter/scipy-notebook:latest
    volumes:
      - </my_local_stl-scraper_folder>:/home/jovyan/work
    ports:
      - '8888:8888'
    networks:
      - elastic           


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - </my_local_stl-scraper_folder>:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic      

networks:
  elastic:
    external: true

```

I have enabled elasticsearch on both stl.ini and stl.ini.dist files:

```
[search]
currency = EUR
roomTypes =

[storage]
; csv or elasticsearch
type = elasticsearch

[airbnb]
api_key = d306zoyjsyarp7ifhu67rjxn52tv0t20

[elasticsearch]
hosts = https://localhost:9200
index = short-term-listings
username = elastic
password = 
ca_cert =
```

Both jupyter-notebook on Python 3 and Elasticsearch seems to be working normally, however when executing `./stl.py search "Madrid, Spain"` from the env activated and requirements installed jupyter-notebook terminal, i get the following elasticsearch message:

```
/home/jovyan/env/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py:395: SecurityWarning: Connecting to 'https://localhost:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(
2023-02-02 10:58:09,763 [WARNING] Node <Urllib3HttpNode(https://localhost:9200)> has failed for 1 times in a row, putting on 1 second timeout
2023-02-02 10:58:09,763 [WARNING] Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/jovyan/env/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/jovyan/env/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7f4c32e36a70>: Failed to establish a new connection: [Errno 111] Connection refused)
2023-02-02 10:58:09,764 [WARNING] Node <Urllib3HttpNode(https://localhost:9200)> has failed for 2 times in a row, putting on 2 second timeout
2023-02-02 10:58:09,764 [WARNING] Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/home/jovyan/env/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/jovyan/env/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7f4c32e36ce0>: Failed to establish a new connection: [Errno 111] Connection refused)
2023-02-02 10:58:09,764 [WARNING] Node <Urllib3HttpNode(https://localhost:9200)> has failed for 3 times in a row, putting on 4 second timeout
2023-02-02 10:58:09,764 [WARNING] Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/home/jovyan/env/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/jovyan/env/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPSConnection object at 0x7f4c32e36ef0>: Failed to establish a new connection: [Errno 111] Connection refused)
2023-02-02 10:58:09,765 [WARNING] Node <Urllib3HttpNode(https://localhost:9200)> has failed for 4 times in a row, putting on 8 second timeout
2023-02-02 10:58:09,765 [CRITICAL] <urllib3.connection.HTTPSConnection object at 0x7f4c32e37100>: Failed to establish a new connection: [Errno 111] Connection refused
Could not connect to elasticsearch.
```
I have no experience with elasticsearch. Do you have any sense of what could be wrong on this setup? Are there any other alternatives to access the Pricing and Calendar functionality?

**Comment by JoeBashe** [comment]
Hello @aTnT, thanks for the detailed writeup 🙏 

> I am trying to access the Calendar and Pricing functionality, which seems to require an elasticsearch database

That is correct!

>  I have written the below `docker-compose.yml` file:

Nice work! 👍 I like the idea of a docker-compose environment for repeatable builds.

> I have enabled elasticsearch on both stl.ini and stl.ini.dist files:

FYI, the `.dist` file is just meant to be distributed with the repo as an example / template. The program only reads the `stl.ini` file.

> Are there any other alternatives to access the Pricing and Calendar functionality?

The `calendar` and `pricing` functionality is currently a work in progress. Because Airbnb pricing can change based on calendar day, number of days booked (weekly discounts, monthly discounts), seasonal discounts, etc., the scraper builds a calendar for each listing and tries to get the estimated day rate for each day. This process is somewhat complicated and hasn't been perfected yet. However to get this level of detail, it is necessary to use elasticsearch rather than a simple csv file.

That said, the normal `search` functionality will get you the advertised nightly rate, which may be all you need for your use case.

> Do you have any sense of what could be wrong on this setup? 

Based on the errors, it looks like the jupyter container was trying to access elasticsearch at https://localhost:9200, but since elasticsearch is in a different container, you need to access it via the container network. On my computer (using Linux), that looks like https://172.17.0.1:9200. On your system, https://elasticsearch:9200 should work. You can change it by changing the `hosts` value under `[elasticsearch]` in the `stl.ini` config file.

I've modified your `docker-compose.yml` file and updated the README.md here: (https://github.com/JoeBashe/stl-scraper/pull/10/files). I will merge it into the project in the next couple days, but wanted to give you a chance to see my changes and see if they work for you and if you have any suggestions. (If you pull my branch (`feature/#9-add-docker-compose-config`), change `hosts` under `[elasticsearch]` in `stl.ini` to https://es01:9200)

Thank again! 👋

**Comment by JoeBashe** [comment]
One additional issue I noticed is your `docker-compose.yml` file is using elasticsearch version 7, but the project depends on using version 8. If you pull my branch and follow the `README.md`, it should work out of the box.

**Comment by aTnT** [comment]
Hi @JoeBashe, thanks for the complete reply and the nice work done! I have tried to spin up the docker compose from the branch, but have been faced with memory issues.

I get stuck because "container for service "es01" is unhealthy". Looking to the `docker compose logs` looks like to be a virtual memory issue. I tried to change `MEM_LIMIT` to fit my available memory, but it didn't help so far. I need some more time to research the source of the problem, so give me a couple of days to come back on this and give you some more feedback.

**Comment by aTnT** [comment]
I solved the memory issues (see [Elasticsearch Container Stopped with Exit code 78](https://github.com/laradock/laradock/issues/1699)) by running the additional command before building/running the containers:

`sudo sysctl -w vm.max_map_count=262144`

I get now an authentication issue with kibana SSL certificates. Python output below:

```
docker compose exec jupyter-scipy-notebook work/.venv/bin/python work/stl.py search -v "Madrid, Spain"
/home/jovyan/work/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py:395: SecurityWarning: Connecting to 'https://es01:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(
/home/jovyan/work/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'es01'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
2023-02-05 23:47:12,437 [INFO] HEAD https://es01:9200/short-term-listings [status:401 duration:0.013s]
Traceback (most recent call last):
  File "/home/jovyan/work/stl.py", line 17, in <module>
    main()
  File "/home/jovyan/work/stl.py", line 10, in main
    StlCommand(arguments).execute()
  File "/home/jovyan/work/stl/command/stl_command.py", line 70, in execute
    persistence = self.__create_persistence(config, project_path, query)
  File "/home/jovyan/work/stl/command/stl_command.py", line 144, in __create_persistence
    persistence.create_index_if_not_exists(config['elasticsearch']['index'])
  File "/home/jovyan/work/stl/persistence/elastic.py", line 81, in create_index_if_not_exists
    if self.__es.indices.exists(index=index_name):
  File "/home/jovyan/work/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/jovyan/work/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/indices.py", line 1064, in exists
    return self.perform_request(  # type: ignore[return-value]
  File "/home/jovyan/work/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 390, in perform_request
    return self._client.perform_request(
  File "/home/jovyan/work/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 321, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.AuthenticationException: AuthenticationException(401, 'None')
```
es-01 container log:

`stl-scraper-es01-1                    | 2023-02-06T00:46:22.030502125Z {"@timestamp":"2023-02-06T00:46:22.030Z", "log.level": "INFO", "message":"Authentication of [kibana_system] was terminated by realm [reserved] - failed to authenticate user [kibana_system]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][transport_worker][T#5]","log.logger":"org.elasticsearch.xpack.security.authc.RealmsAuthenticator","trace.id":"728c4465eac08c7afb8a485245dcecd4","elasticsearch.cluster.uuid":"FEA2o8YcT1a9qEboCaC07A","elasticsearch.node.id":"RgBzp6XOQmOB71eG0bXNqg","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"es-docker-cluster"}`

**Comment by JoeBashe** [comment]
It looks like the issue is due to authentication at this point. Did you create the `.env` config file before building the container? You need to create the `.env` file from `.env.dist`, similar to what you did with the `stl.ini` file. Also, in your `stl.ini` file under `[elasticsearch]`, your username should be `elastic` and password should be `abc123` (it should match what's in the `.env` file).

I intend to clean up the configuration and move it all into the `.env` file, but the above instructions should hopefully work for now.

**Comment by aTnT** [comment]
Yes, i have both `.env` and `stl.ini` with matching passwords and changed also `hosts = https://es01:9200`, see below. To be sure, i just did a new repo clone from scratch to make sure i had the changes made to main branch about 5 days ago, but the problem persists. 

What do you use after `ca_cert = ` in `stl.ini`? I have tried `config/certs/ca/ca.crt`, `certs`, `${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}` but none worked.

.env:

```
# Password for the 'elastic' user (at least 6 characters)
ELASTIC_PASSWORD=abc123

# Password for the 'kibana_system' user (at least 6 characters)
KIBANA_PASSWORD=abc123

# Version of Elastic products
STACK_VERSION=8.6.1

# Set the cluster name
CLUSTER_NAME=es-docker-cluster

# Set to 'basic' or 'trial' to automatically start the 30-day trial
LICENSE=basic
#LICENSE=trial

# Port to expose Elasticsearch HTTP API to the host
ES_PORT=9200
#ES_PORT=127.0.0.1:9200

# Port to expose Kibana to the host
KIBANA_PORT=5601
#KIBANA_PORT=80

# Increase or decrease based on the available host memory (in bytes)
MEM_LIMIT=1073741824

# Project namespace (defaults to the current folder name if not set)
#COMPOSE_PROJECT_NAME=myproject
```


stl.ini:
```

[search]
currency = EUR
roomTypes =

[storage]
; csv or elasticsearch
type = elasticsearch

[airbnb]
api_key = d306zoyjsyarp7ifhu67rjxn52tv0t20

[elasticsearch]
hosts = https://es01:9200
index = short-term-listings
username = elastic
password = abc123
ca_cert =

```

**Comment by JoeBashe** [comment]
Hi @aTnT, sorry for the delay.

Here is my `.env`:

```
# Password for the 'elastic' user (at least 6 characters)
ELASTIC_PASSWORD=abc123

# Password for the 'kibana_system' user (at least 6 characters)
KIBANA_PASSWORD=abc123

# Version of Elastic products
STACK_VERSION=8.6.1

# Set the cluster name
CLUSTER_NAME=es-docker-cluster

# Set to 'basic' or 'trial' to automatically start the 30-day trial
LICENSE=basic
#LICENSE=trial

# Port to expose Elasticsearch HTTP API to the host
ES_PORT=9200
#ES_PORT=127.0.0.1:9200

# Port to expose Kibana to the host
KIBANA_PORT=5601
#KIBANA_PORT=80

# Increase or decrease based on the available host memory (in bytes)
MEM_LIMIT=1073741824

# Project namespace (defaults to the current folder name if not set)
#COMPOSE_PROJECT_NAME=myproject
```

and `stl.ini`

```
[search]
currency = USD
roomTypes = "Entire home/apt"

[storage]
type = elasticsearch

[airbnb]
api_key = d306zoyjsyarp7ifhu67rjxn52tv0t20

[elasticsearch]
hosts = https://es01:9200
index = short-term-listings
username = elastic
password = abc123

ca_cert = /usr/share/elasticsearch/config/certs/ca/ca.crt
```

Hope that helps.

**Comment by JoeBashe** [comment]
FYI, I have also updated the feature branch to use `conda` for installing packages instead of pip
